name: API tests

on:
  push:
    branches: ["main"]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman + HTML reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Smoke tests
        run: |
          newman run collections/smoke.json \
            -e environments/dev.json \
            -r htmlextra \
            --reporter-htmlextra-export reports/smoke-report.html

      - name: Upload Smoke HTML report
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: reports/smoke-report.html
      
  
        
    
